version: '3.8'

services:
  db:
    image: postgres:13
    container_name: codehive_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: snippetsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Script para povoar o banco

volumes:
  postgres_data: