version: '3.8'

services:
  db:
    image: postgres:13
    container_name: codehive_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: snippetsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: codehive_backend
    ports:
      - "3333:3333"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/snippetsdb
    depends_on:
      - db

volumes:
  postgres_data: